apiVersion: apps/v1


kind: Deployment
metadata:
  labels:
    app: prediction-cout
  name: prediction-cout
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: prediction-cout
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prediction-cout
    spec:
      containers:
      - name: prediction-cout
        image: wassim97/projet_cloud_prediction_cout
        imagePullPolicy: Always
        ports:
          containerPort: 8000
