apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prediction-cout
  name: prediction-cout
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: prediction-cout
  template:
    metadata:
      labels:
        app: prediction-cout
    spec:
      containers:
      - name: prediction-cout
        image: wassim97/projet_cloud_prediction_cout
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 8000
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi #256Mi 
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: prediction-cout
  name: prediction-cout
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP # nodePort: 30702 #CHANGE
    port: 8000 #CHANGE
    targetPort: 8000 #CHANGE 
  selector:
    app: prediction-cout
  
